-- DROP TABLE IF EXISTS user;
--
-- CREATE TABLE user (
--   id BIGINT(19)	 AUTO_INCREMENT  PRIMARY KEY,
--   ACTIVE_STATUS BOOLEAN(1) NOT NULL,
--   AGE INTEGER(10) NOT NULL,
--   GRADE VARCHAR(255) NOT NULL,
--   NAME VARCHAR(255) NOT NULL
-- );
--
-- INSERT INTO user (id, active_status, age, grade, name) VALUES ('1', '1', 32, 'VIP', 'THEO KO');
-- INSERT INTO user (id, active_status, age, grade, name) VALUES ('2', '1', 2, 'VIP', 'BABY');
-- INSERT INTO user (id, active_status, age, grade, name) VALUES ('3', '1', 31, 'VIP', 'SARU LIM');
-- INSERT INTO user (id, active_status, age, grade, name) VALUES ('4', '1', 0, 'VIP', 'SAMY');